name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: latest

      - name: Test
        run: go test -v ./...

      - name: Run coverage
        run: go test -race -coverprofile=coverage.txt -covermode=atomic ./lib
      
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          token: 096d3378-eeb2-4970-b921-cb308aef09b6
