name: deploy_ci

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Registry
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push Docker image tag version
        uses: docker/build-push-action@v2.3.0
        with:
          push: true
          tags: flagshipio/sync-agent:${{ github.event.release.tag_name }}
          context: .
          file: ./Dockerfile

      - name: Build and push Docker image tag latest
        uses: docker/build-push-action@v2.3.0
        with:
          push: true
          tags: flagshipio/sync-agent:latest
          context: .
          file: ./Dockerfile

  add-releases-assets-binary:
    name: Release Go Binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # build and publish in parallel: linux/386, linux/amd64, linux/arm64
        goos: [linux]
        goarch: ["386", amd64, arm64]
    steps:
      - uses: actions/checkout@v3
      - uses: wangyoucao577/go-release-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          goversion: "https://dl.google.com/go/go1.20.5.linux-amd64.tar.gz"
          sha256sum: true
          extra_files: readme.md
